<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MtuhaDiagnosesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * To run: php artisan db:seed --class=Database\\Seeders\\MtuhaDiagnosesSeeder
     */
    public function run()
    {
        $rows = [
            [ 'id' => 0, 'catname' => 'Symptoms' ],
            [ 'id' => 4, 'catname' => 'Hepatitis B' ],
            [ 'id' => 5, 'catname' => 'Hepatitis C' ],
            [ 'id' => 6, 'catname' => 'Septicaemia Unspecified' ],
            [ 'id' => 7, 'catname' => 'Diarrhea with no dehydration' ],
            [ 'id' => 8, 'catname' => 'Diarrhea with some dehydration' ],
            [ 'id' => 9, 'catname' => 'Human Africa Trypanosomiasis' ],
            [ 'id' => 10, 'catname' => 'Urogenital Schistosomiasis' ],
            [ 'id' => 11, 'catname' => 'Intestinal Schistosomiasis' ],
            [ 'id' => 12, 'catname' => 'Lympahtic Filariasis - Hydrocele' ],
            [ 'id' => 13, 'catname' => 'Lympahtic Filariasis - Lymphoedema' ],
            [ 'id' => 15, 'catname' => 'Suspected Onchocerciasis (River Blindness)' ],
            [ 'id' => 16, 'catname' => 'Amoebiasis' ],
            [ 'id' => 17, 'catname' => 'STH (Trichuris, Hookworm, Ascaris)' ],
            [ 'id' => 18, 'catname' => 'Sexually Transmitted Infections, Others' ],
            [ 'id' => 19, 'catname' => 'Tuberculosis' ],
            [ 'id' => 20, 'catname' => 'Other Infections and parasite diseases' ],
            [ 'id' => 21, 'catname' => 'Neoplasim/Cancer unspecified' ],
            [ 'id' => 22, 'catname' => 'Anaemia, Mild/Moderate' ],
            [ 'id' => 23, 'catname' => 'Anaemia, Severe' ],
            [ 'id' => 24, 'catname' => 'Iron deficiency anaemia' ],
            [ 'id' => 25, 'catname' => 'Sickle cell Diseases' ],
            [ 'id' => 26, 'catname' => 'Other diseases of blood and blood forming organs' ],
            [ 'id' => 27, 'catname' => 'Diabetes' ],
            [ 'id' => 28, 'catname' => 'Severe wasting with Nutritional Edema' ],
            [ 'id' => 29, 'catname' => 'Severe wasting without Nutritional Edema' ],
            [ 'id' => 30, 'catname' => 'Goiter' ],
            [ 'id' => 31, 'catname' => 'Other thyroid diseases' ],
            [ 'id' => 32, 'catname' => 'Moderate Wasting' ],
            [ 'id' => 33, 'catname' => 'Obesity' ],
            [ 'id' => 34, 'catname' => 'Vitamin A Deficiency' ],
            [ 'id' => 35, 'catname' => 'Other Endocrine, Nutritional and Metabolic diseases' ],
            [ 'id' => 36, 'catname' => 'Schizophrenia' ],
            [ 'id' => 37, 'catname' => 'Epilepsy' ],
            [ 'id' => 38, 'catname' => 'Neurosis' ],
            [ 'id' => 39, 'catname' => 'Substance abuse' ],
            [ 'id' => 40, 'catname' => 'Other Mental and behavioural disorders' ],
            [ 'id' => 41, 'catname' => 'Cerebral palsy' ],
            [ 'id' => 42, 'catname' => 'Other nervous system disorders' ],
            [ 'id' => 43, 'catname' => 'Eye diseases, Infectious' ],
            [ 'id' => 44, 'catname' => 'Eye diseases, Non infectious' ],
            [ 'id' => 45, 'catname' => 'Eye disease, Injuries' ],
            [ 'id' => 46, 'catname' => 'Other eye diseases' ],
            [ 'id' => 47, 'catname' => 'Ear infections, Acute' ],
            [ 'id' => 48, 'catname' => 'Ear infections, Chronic' ],
            [ 'id' => 49, 'catname' => 'Other diseases of ear and mastoid process' ],
            [ 'id' => 50, 'catname' => 'Hypertension' ],
            [ 'id' => 51, 'catname' => 'Rheumatic Heart diseases' ],
            [ 'id' => 52, 'catname' => 'Other diseases of the circulatory system' ],
            [ 'id' => 53, 'catname' => 'Upper Respiratory Infections (Pharyngitis, Tonsillitis, Rhinitis)' ],
            [ 'id' => 54, 'catname' => 'Pneumonia' ],
            [ 'id' => 55, 'catname' => 'Bronchial Asthma ' ],
            [ 'id' => 56, 'catname' => 'Acute Bronchitis' ],
            [ 'id' => 57, 'catname' => 'Other respiratory diseases' ],
            [ 'id' => 58, 'catname' => 'Appendicitis' ],
            [ 'id' => 59, 'catname' => 'Hernia, unspecified' ],
            [ 'id' => 60, 'catname' => 'Hemorrhoids' ],
            [ 'id' => 61, 'catname' => 'Peptic Ulcers' ],
            [ 'id' => 62, 'catname' => 'GIT Diseases, other Non-infectious' ],
            [ 'id' => 63, 'catname' => 'Dental Caries' ],
            [ 'id' => 64, 'catname' => 'Periodontal Diseases' ],
            [ 'id' => 65, 'catname' => 'Dental Condition, Other' ],
            [ 'id' => 66, 'catname' => 'Dental Abscess' ],
            [ 'id' => 67, 'catname' => 'Other digestive diseases' ],
            [ 'id' => 68, 'catname' => 'Skin infection, Non-Fungal' ],
            [ 'id' => 69, 'catname' => 'Skin infection, Fungal' ],
            [ 'id' => 70, 'catname' => 'Skin Diseases, Non-infectious' ],
            [ 'id' => 71, 'catname' => 'Fungal Infection, Non-skin' ],
            [ 'id' => 72, 'catname' => 'Other skin and subcutaneous tissue diseases' ],
            [ 'id' => 73, 'catname' => 'Gout' ],
            [ 'id' => 74, 'catname' => 'Osteomyelitis' ],
            [ 'id' => 75, 'catname' => 'Rheumatoid and Joint Diseases' ],
            [ 'id' => 76, 'catname' => 'Cellulitis' ],
            [ 'id' => 77, 'catname' => 'Soft tissue injury' ],
            [ 'id' => 78, 'catname' => 'Other diseases of the Musculoskeletal system' ],
            [ 'id' => 79, 'catname' => 'Urinary Tact Infections {UTI}' ],
            [ 'id' => 80, 'catname' => 'Acute Kidney Disease (AKI)' ],
            [ 'id' => 81, 'catname' => 'Bartholin Abscess' ],
            [ 'id' => 82, 'catname' => 'Benign prostatic Hyperplasia (BPH)' ],
            [ 'id' => 83, 'catname' => 'Nephrotic syndrome (Unspecified)' ],
            [ 'id' => 84, 'catname' => 'Pelvic Inflammatory disease (PID)' ],
            [ 'id' => 85, 'catname' => 'STI Genital Discharge Syndrome (GDS)' ],
            [ 'id' => 86, 'catname' => 'STI Genital Ulcer Disease (GUD)' ],
            [ 'id' => 87, 'catname' => 'Other diseases of the Genital-Urinary and Pelvic system' ],
            [ 'id' => 88, 'catname' => 'Gynaecological diseases, Others' ],
            [ 'id' => 89, 'catname' => 'Cystitis' ],
            [ 'id' => 90, 'catname' => 'Ectopic Pregnancy' ],
            [ 'id' => 91, 'catname' => 'Abortion' ],
            [ 'id' => 92, 'catname' => 'Pregnancy Complications' ],
            [ 'id' => 93, 'catname' => 'Pueperal sepsis' ],
            [ 'id' => 94, 'catname' => 'Cracked Nipple' ],
            [ 'id' => 95, 'catname' => 'Other Pregnancy, Childbirth and Pueperal diseases' ],
            [ 'id' => 96, 'catname' => 'Neonatal sepsis' ],
            [ 'id' => 97, 'catname' => 'Low birth weight and Prematurity' ],
            [ 'id' => 98, 'catname' => 'Birth asphyxia' ],
            [ 'id' => 99, 'catname' => 'Other certain conditions originating in the perinatal period' ],
            [ 'id' => 100, 'catname' => 'Congenital Hydrocephalus' ],
            [ 'id' => 101, 'catname' => 'Other Congenital Disorders' ],
            [ 'id' => 102, 'catname' => 'Burn' ],
            [ 'id' => 103, 'catname' => 'Fractures' ],
            [ 'id' => 104, 'catname' => 'Poisoning' ],
            [ 'id' => 105, 'catname' => 'Dislocations (Unspecified)' ],
            [ 'id' => 106, 'catname' => 'Sprain/Strain' ],
            [ 'id' => 107, 'catname' => 'Alcohol Intoxication' ],
            [ 'id' => 108, 'catname' => 'Snake Bites' ],
            [ 'id' => 109, 'catname' => 'Insect Bites' ],
            [ 'id' => 110, 'catname' => 'Animal Bite (Non Suspected Rabies)' ],
            [ 'id' => 111, 'catname' => 'Other injury, poisoning and certain others' ],
            [ 'id' => 112, 'catname' => 'Road Traffic Accidents' ],
            [ 'id' => 113, 'catname' => 'Assault (Unspecified)' ],
            [ 'id' => 114, 'catname' => 'Drowning' ],
            [ 'id' => 115, 'catname' => 'Other external causes of morbidity' ],
            [ 'id' => 116, 'catname' => 'Waliopewa rufaa' ],
            [ 'id' => 117, 'catname' => 'Waliofariki OPD' ],
            [ 'id' => 118, 'catname' => 'Waliotibiwa kwa Bima ya Afya - NHIF' ],
            [ 'id' => 119, 'catname' => 'Waliotibiwa kwa Bima ya CHF' ],
            [ 'id' => 120, 'catname' => 'Waliotibiwa kwa kutumia Bima nyingine' ],
            [ 'id' => 121, 'catname' => 'Waliotibiwa Pesa taslimu (Cash)' ],
            [ 'id' => 122, 'catname' => 'Waliotibiwa kwa Msamaha' ],
        ];

        // Use insertOrIgnore to avoid duplicate errors if seed rerun
        DB::table('mtuha_diagnoses')->insertOrIgnore($rows);

        $this->command->info('Inserted ' . count($rows) . ' mtuha diagnosis rows');
    }
}
