<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('idsr_diagnoses')) {
            Schema::create('idsr_diagnoses', function (Blueprint $table) {
                $table->id();
                $table->string('name', 90);
                $table->timestamps();
            });
        }

        if (!Schema::hasTable('idsr_icd_mapping')) {
            Schema::create('idsr_icd_mapping', function (Blueprint $table) {
                $table->id();
                $table->foreignId('idsr_diagnosis_id')->constrained('idsr_diagnoses')->cascadeOnDelete();
                $table->string('icd_code', 11);
                $table->tinyInteger('status')->default(1);
                $table->timestamps();
                $table->index('icd_code', 'idsr_icd_mapping_icd_code_index');
            });
        }

        $now = now();

        if (DB::table('idsr_diagnoses')->count() === 0) {
            $diagnoses = [
                ['id' => 1, 'name' => 'Acute Viral Hemorrhagic Fevers (VHF)'],
                ['id' => 2, 'name' => 'Adverse Effects Following Immunization (AEFI)'],
                ['id' => 3, 'name' => 'Aflatoxicosis'],
                ['id' => 4, 'name' => 'Anthrax'],
                ['id' => 5, 'name' => 'Bacterial Meningitis (BM)'],
                ['id' => 6, 'name' => 'Chikungunya'],
                ['id' => 7, 'name' => 'Cholera'],
                ['id' => 8, 'name' => 'COVID-19'],
                ['id' => 9, 'name' => 'Dengue Fever'],
                ['id' => 10, 'name' => 'Diarrhea with Blood (Dysentery)'],
                ['id' => 11, 'name' => 'Ebola or Marburg virus diseases'],
                ['id' => 12, 'name' => 'Human Brucellosis'],
                ['id' => 13, 'name' => 'Human Influenza caused by new subtype'],
                ['id' => 14, 'name' => 'Lassa nad Crimean-Congo Hemorrhagic Fever (CCHF)'],
                ['id' => 15, 'name' => 'Listeriosis'],
                ['id' => 16, 'name' => 'Malaria**'],
                ['id' => 17, 'name' => 'Measles'],
                ['id' => 18, 'name' => 'Middle East Respiratory Syndrome Coronavirus (MERS CoV)'],
                ['id' => 19, 'name' => 'Neonatal Tetanus (NNT)'],
                ['id' => 20, 'name' => 'Plague'],
                ['id' => 21, 'name' => 'Poliomyolitis (Acute flaccid paralysis AFP)'],
                ['id' => 22, 'name' => 'Rabies (Human)'],
                ['id' => 23, 'name' => 'Rift Valley Fever (RVF)'],
                ['id' => 24, 'name' => 'Severe Acute Respiratory Infections (SARI)*'],
                ['id' => 25, 'name' => 'Severe Acute Respiratory Syndrome (SARS)'],
                ['id' => 26, 'name' => 'Small Pox'],
                ['id' => 27, 'name' => 'Trypanosomiasis'],
                ['id' => 28, 'name' => 'Yellow Fever'],
                ['id' => 29, 'name' => 'Zika virus diseases'],
                ['id' => 30, 'name' => 'Diarrhea with dehydration in children less than five years of age'],
                ['id' => 31, 'name' => 'Severe Pneumonia <5 years'],
                ['id' => 32, 'name' => 'Animal Bites'],
                ['id' => 33, 'name' => 'Malaria***'],
                ['id' => 34, 'name' => 'Typhoid'],
                ['id' => 35, 'name' => 'Snake Bites'],
            ];

            DB::table('idsr_diagnoses')->insert(array_map(
                fn ($row) => $row + ['created_at' => $now, 'updated_at' => $now],
                $diagnoses
            ));
        }

        if (DB::table('idsr_icd_mapping')->count() === 0) {
            $mappings = [
                ['id' => 1, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A96', 'status' => 1],
                ['id' => 2, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A96.0', 'status' => 1],
                ['id' => 3, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A96.1', 'status' => 1],
                ['id' => 4, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A96.8', 'status' => 1],
                ['id' => 5, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A96.9', 'status' => 1],
                ['id' => 6, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A98', 'status' => 1],
                ['id' => 7, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A98.1', 'status' => 1],
                ['id' => 8, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A98.2', 'status' => 1],
                ['id' => 9, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A98.5', 'status' => 1],
                ['id' => 10, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A98.8', 'status' => 1],
                ['id' => 11, 'idsr_diagnosis_id' => 1, 'icd_code' => 'A99', 'status' => 1],
                ['id' => 12, 'idsr_diagnosis_id' => 2, 'icd_code' => 'M02.2', 'status' => 1],
                ['id' => 13, 'idsr_diagnosis_id' => 3, 'icd_code' => 'T64', 'status' => 1],
                ['id' => 14, 'idsr_diagnosis_id' => 4, 'icd_code' => 'A22', 'status' => 1],
                ['id' => 15, 'idsr_diagnosis_id' => 4, 'icd_code' => 'A22.0', 'status' => 1],
                ['id' => 16, 'idsr_diagnosis_id' => 4, 'icd_code' => 'A22.1', 'status' => 1],
                ['id' => 17, 'idsr_diagnosis_id' => 4, 'icd_code' => 'A22.2', 'status' => 1],
                ['id' => 18, 'idsr_diagnosis_id' => 4, 'icd_code' => 'A22.7', 'status' => 1],
                ['id' => 19, 'idsr_diagnosis_id' => 4, 'icd_code' => 'A22.8', 'status' => 1],
                ['id' => 20, 'idsr_diagnosis_id' => 4, 'icd_code' => 'A22.9', 'status' => 1],
                ['id' => 21, 'idsr_diagnosis_id' => 5, 'icd_code' => 'A39.0', 'status' => 1],
                ['id' => 22, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G00', 'status' => 1],
                ['id' => 23, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G00.0', 'status' => 1],
                ['id' => 24, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G00.1', 'status' => 1],
                ['id' => 25, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G00.2', 'status' => 1],
                ['id' => 26, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G00.3', 'status' => 1],
                ['id' => 27, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G00.8', 'status' => 1],
                ['id' => 28, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G00.9', 'status' => 1],
                ['id' => 29, 'idsr_diagnosis_id' => 5, 'icd_code' => 'G01', 'status' => 1],
                ['id' => 30, 'idsr_diagnosis_id' => 6, 'icd_code' => 'A92.0', 'status' => 1],
                ['id' => 31, 'idsr_diagnosis_id' => 7, 'icd_code' => 'A00', 'status' => 1],
                ['id' => 32, 'idsr_diagnosis_id' => 7, 'icd_code' => 'A00.0', 'status' => 1],
                ['id' => 33, 'idsr_diagnosis_id' => 7, 'icd_code' => 'A00.1', 'status' => 1],
                ['id' => 34, 'idsr_diagnosis_id' => 7, 'icd_code' => 'A00.9', 'status' => 1],
                ['id' => 35, 'idsr_diagnosis_id' => 8, 'icd_code' => 'B34.2', 'status' => 1],
                ['id' => 36, 'idsr_diagnosis_id' => 8, 'icd_code' => 'B97.2', 'status' => 1],
                ['id' => 38, 'idsr_diagnosis_id' => 9, 'icd_code' => 'A90', 'status' => 1],
                ['id' => 39, 'idsr_diagnosis_id' => 9, 'icd_code' => 'A91', 'status' => 1],
                ['id' => 40, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A03', 'status' => 1],
                ['id' => 41, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A03.0', 'status' => 1],
                ['id' => 42, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A03.1', 'status' => 1],
                ['id' => 43, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A03.2', 'status' => 1],
                ['id' => 44, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A03.3', 'status' => 1],
                ['id' => 45, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A03.8', 'status' => 1],
                ['id' => 46, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A03.9', 'status' => 1],
                ['id' => 47, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A06', 'status' => 1],
                ['id' => 48, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A06.0', 'status' => 1],
                ['id' => 49, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A06.9', 'status' => 1],
                ['id' => 50, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A07.0', 'status' => 1],
                ['id' => 51, 'idsr_diagnosis_id' => 10, 'icd_code' => 'A07.1', 'status' => 1],
                ['id' => 52, 'idsr_diagnosis_id' => 11, 'icd_code' => 'A98.3', 'status' => 1],
                ['id' => 53, 'idsr_diagnosis_id' => 11, 'icd_code' => 'A98.4', 'status' => 1],
                ['id' => 54, 'idsr_diagnosis_id' => 12, 'icd_code' => 'A23', 'status' => 1],
                ['id' => 55, 'idsr_diagnosis_id' => 12, 'icd_code' => 'A23.0', 'status' => 1],
                ['id' => 56, 'idsr_diagnosis_id' => 12, 'icd_code' => 'A23.1', 'status' => 1],
                ['id' => 57, 'idsr_diagnosis_id' => 12, 'icd_code' => 'A23.2', 'status' => 1],
                ['id' => 58, 'idsr_diagnosis_id' => 12, 'icd_code' => 'A23.3', 'status' => 1],
                ['id' => 59, 'idsr_diagnosis_id' => 12, 'icd_code' => 'A23.8', 'status' => 1],
                ['id' => 60, 'idsr_diagnosis_id' => 12, 'icd_code' => 'A23.9', 'status' => 1],
                ['id' => 61, 'idsr_diagnosis_id' => 13, 'icd_code' => 'J09', 'status' => 1],
                ['id' => 62, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J10', 'status' => 1],
                ['id' => 63, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J10.0', 'status' => 1],
                ['id' => 64, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J10.1', 'status' => 1],
                ['id' => 65, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J10.8', 'status' => 1],
                ['id' => 66, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J11', 'status' => 1],
                ['id' => 67, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J11.0', 'status' => 1],
                ['id' => 68, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J11.1', 'status' => 1],
                ['id' => 69, 'idsr_diagnosis_id' => 24, 'icd_code' => 'J11.8', 'status' => 1],
                ['id' => 70, 'idsr_diagnosis_id' => 14, 'icd_code' => 'A96.2', 'status' => 1],
                ['id' => 71, 'idsr_diagnosis_id' => 14, 'icd_code' => 'A98.0', 'status' => 1],
                ['id' => 72, 'idsr_diagnosis_id' => 15, 'icd_code' => 'A32', 'status' => 1],
                ['id' => 73, 'idsr_diagnosis_id' => 15, 'icd_code' => 'A32.0', 'status' => 1],
                ['id' => 74, 'idsr_diagnosis_id' => 15, 'icd_code' => 'A32.1', 'status' => 1],
                ['id' => 75, 'idsr_diagnosis_id' => 15, 'icd_code' => 'A32.7', 'status' => 1],
                ['id' => 76, 'idsr_diagnosis_id' => 15, 'icd_code' => 'A32.8', 'status' => 1],
                ['id' => 77, 'idsr_diagnosis_id' => 15, 'icd_code' => 'A32.9', 'status' => 1],
                ['id' => 78, 'idsr_diagnosis_id' => 15, 'icd_code' => 'P37.2', 'status' => 1],
                ['id' => 79, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05', 'status' => 1],
                ['id' => 80, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05.0', 'status' => 1],
                ['id' => 81, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05.1', 'status' => 1],
                ['id' => 82, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05.2', 'status' => 1],
                ['id' => 83, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05.3', 'status' => 1],
                ['id' => 84, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05.4', 'status' => 1],
                ['id' => 85, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05.8', 'status' => 1],
                ['id' => 86, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B05.9', 'status' => 1],
                ['id' => 87, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B06', 'status' => 1],
                ['id' => 88, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B06.0', 'status' => 1],
                ['id' => 89, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B06.8', 'status' => 1],
                ['id' => 90, 'idsr_diagnosis_id' => 17, 'icd_code' => 'B06.9', 'status' => 1],
                ['id' => 91, 'idsr_diagnosis_id' => 19, 'icd_code' => 'A33', 'status' => 1],
                ['id' => 92, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20', 'status' => 1],
                ['id' => 93, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20.0', 'status' => 1],
                ['id' => 94, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20.1', 'status' => 1],
                ['id' => 95, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20.2', 'status' => 1],
                ['id' => 96, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20.3', 'status' => 1],
                ['id' => 97, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20.7', 'status' => 1],
                ['id' => 98, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20.8', 'status' => 1],
                ['id' => 99, 'idsr_diagnosis_id' => 20, 'icd_code' => 'A20.9', 'status' => 1],
                ['id' => 100, 'idsr_diagnosis_id' => 21, 'icd_code' => 'A80', 'status' => 1],
                ['id' => 101, 'idsr_diagnosis_id' => 21, 'icd_code' => 'A80.0', 'status' => 1],
                ['id' => 102, 'idsr_diagnosis_id' => 21, 'icd_code' => 'A80.1', 'status' => 1],
                ['id' => 103, 'idsr_diagnosis_id' => 21, 'icd_code' => 'A80.2', 'status' => 1],
                ['id' => 104, 'idsr_diagnosis_id' => 21, 'icd_code' => 'A80.3', 'status' => 1],
                ['id' => 105, 'idsr_diagnosis_id' => 21, 'icd_code' => 'A80.4', 'status' => 1],
                ['id' => 106, 'idsr_diagnosis_id' => 21, 'icd_code' => 'A80.9', 'status' => 1],
                ['id' => 107, 'idsr_diagnosis_id' => 22, 'icd_code' => 'A82', 'status' => 1],
                ['id' => 108, 'idsr_diagnosis_id' => 22, 'icd_code' => 'A82.0', 'status' => 1],
                ['id' => 109, 'idsr_diagnosis_id' => 22, 'icd_code' => 'A82.1', 'status' => 1],
                ['id' => 110, 'idsr_diagnosis_id' => 22, 'icd_code' => 'A82.9', 'status' => 1],
                ['id' => 111, 'idsr_diagnosis_id' => 23, 'icd_code' => 'A92.4', 'status' => 1],
                ['id' => 112, 'idsr_diagnosis_id' => 26, 'icd_code' => 'B03', 'status' => 1],
                ['id' => 113, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B56', 'status' => 1],
                ['id' => 114, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B56.0', 'status' => 1],
                ['id' => 115, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B56.1', 'status' => 1],
                ['id' => 116, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B56.9', 'status' => 1],
                ['id' => 117, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B57', 'status' => 1],
                ['id' => 118, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B57.0', 'status' => 1],
                ['id' => 119, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B57.1', 'status' => 1],
                ['id' => 120, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B57.2', 'status' => 1],
                ['id' => 121, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B57.3', 'status' => 1],
                ['id' => 122, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B57.4', 'status' => 1],
                ['id' => 123, 'idsr_diagnosis_id' => 27, 'icd_code' => 'B57.5', 'status' => 1],
                ['id' => 124, 'idsr_diagnosis_id' => 28, 'icd_code' => 'A95', 'status' => 1],
                ['id' => 125, 'idsr_diagnosis_id' => 28, 'icd_code' => 'A95.0', 'status' => 1],
                ['id' => 126, 'idsr_diagnosis_id' => 28, 'icd_code' => 'A95.1', 'status' => 1],
                ['id' => 127, 'idsr_diagnosis_id' => 28, 'icd_code' => 'A95.9', 'status' => 1],
                ['id' => 128, 'idsr_diagnosis_id' => 29, 'icd_code' => 'A92.8', 'status' => 1],
                ['id' => 129, 'idsr_diagnosis_id' => 30, 'icd_code' => 'BrD02', 'status' => 1],
                ['id' => 130, 'idsr_diagnosis_id' => 30, 'icd_code' => 'BrD03', 'status' => 1],
                ['id' => 131, 'idsr_diagnosis_id' => 31, 'icd_code' => 'BrP01', 'status' => 1],
                ['id' => 132, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53', 'status' => 1],
                ['id' => 133, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.0', 'status' => 1],
                ['id' => 134, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.1', 'status' => 1],
                ['id' => 135, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.2', 'status' => 1],
                ['id' => 136, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.3', 'status' => 1],
                ['id' => 137, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.4', 'status' => 1],
                ['id' => 138, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.5', 'status' => 1],
                ['id' => 139, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.6', 'status' => 1],
                ['id' => 140, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.7', 'status' => 1],
                ['id' => 141, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.8', 'status' => 1],
                ['id' => 142, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W53.9', 'status' => 1],
                ['id' => 143, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54', 'status' => 1],
                ['id' => 144, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.0', 'status' => 1],
                ['id' => 145, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.1', 'status' => 1],
                ['id' => 146, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.2', 'status' => 1],
                ['id' => 147, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.3', 'status' => 1],
                ['id' => 148, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.4', 'status' => 1],
                ['id' => 149, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.5', 'status' => 1],
                ['id' => 150, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.6', 'status' => 1],
                ['id' => 151, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.7', 'status' => 1],
                ['id' => 152, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.8', 'status' => 1],
                ['id' => 153, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W54.9', 'status' => 1],
                ['id' => 154, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55', 'status' => 1],
                ['id' => 155, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.0', 'status' => 1],
                ['id' => 156, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.1', 'status' => 1],
                ['id' => 157, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.2', 'status' => 1],
                ['id' => 158, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.3', 'status' => 1],
                ['id' => 159, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.4', 'status' => 1],
                ['id' => 160, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.5', 'status' => 1],
                ['id' => 161, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.6', 'status' => 1],
                ['id' => 162, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.7', 'status' => 1],
                ['id' => 163, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.8', 'status' => 1],
                ['id' => 164, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W55.9', 'status' => 1],
                ['id' => 165, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56', 'status' => 1],
                ['id' => 166, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.0', 'status' => 1],
                ['id' => 167, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.1', 'status' => 1],
                ['id' => 168, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.2', 'status' => 1],
                ['id' => 169, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.3', 'status' => 1],
                ['id' => 170, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.4', 'status' => 1],
                ['id' => 171, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.5', 'status' => 1],
                ['id' => 172, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.6', 'status' => 1],
                ['id' => 173, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.7', 'status' => 1],
                ['id' => 174, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.8', 'status' => 1],
                ['id' => 175, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W56.9', 'status' => 1],
                ['id' => 176, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58', 'status' => 1],
                ['id' => 177, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.0', 'status' => 1],
                ['id' => 178, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.1', 'status' => 1],
                ['id' => 179, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.2', 'status' => 1],
                ['id' => 180, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.3', 'status' => 1],
                ['id' => 181, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.4', 'status' => 1],
                ['id' => 182, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.5', 'status' => 1],
                ['id' => 183, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.6', 'status' => 1],
                ['id' => 184, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.7', 'status' => 1],
                ['id' => 185, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.8', 'status' => 1],
                ['id' => 186, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W58.9', 'status' => 1],
                ['id' => 187, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59', 'status' => 1],
                ['id' => 188, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.0', 'status' => 1],
                ['id' => 189, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.1', 'status' => 1],
                ['id' => 190, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.2', 'status' => 1],
                ['id' => 191, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.3', 'status' => 1],
                ['id' => 192, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.4', 'status' => 1],
                ['id' => 193, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.5', 'status' => 1],
                ['id' => 194, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.6', 'status' => 1],
                ['id' => 195, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.7', 'status' => 1],
                ['id' => 196, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.8', 'status' => 1],
                ['id' => 197, 'idsr_diagnosis_id' => 32, 'icd_code' => 'W59.9', 'status' => 1],
                ['id' => 198, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B50', 'status' => 1],
                ['id' => 199, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B50.0', 'status' => 1],
                ['id' => 200, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B50.8', 'status' => 1],
                ['id' => 201, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B50.9', 'status' => 1],
                ['id' => 202, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B51', 'status' => 1],
                ['id' => 203, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B51.0', 'status' => 1],
                ['id' => 204, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B51.8', 'status' => 1],
                ['id' => 205, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B51.9', 'status' => 1],
                ['id' => 206, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B52', 'status' => 1],
                ['id' => 207, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B52.0', 'status' => 1],
                ['id' => 208, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B52.8', 'status' => 1],
                ['id' => 209, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B52.9', 'status' => 1],
                ['id' => 210, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B53', 'status' => 1],
                ['id' => 211, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B53.0', 'status' => 1],
                ['id' => 212, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B53.1', 'status' => 1],
                ['id' => 213, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B53.8', 'status' => 1],
                ['id' => 214, 'idsr_diagnosis_id' => 33, 'icd_code' => 'B54', 'status' => 1],
                ['id' => 215, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A01', 'status' => 1],
                ['id' => 216, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A01.0', 'status' => 1],
                ['id' => 217, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A01.1', 'status' => 1],
                ['id' => 218, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A01.2', 'status' => 1],
                ['id' => 219, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A01.3', 'status' => 1],
                ['id' => 220, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A01.4', 'status' => 1],
                ['id' => 221, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A02', 'status' => 1],
                ['id' => 222, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A02.0', 'status' => 1],
                ['id' => 223, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A02.1', 'status' => 1],
                ['id' => 224, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A02.2', 'status' => 1],
                ['id' => 225, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A02.8', 'status' => 1],
                ['id' => 226, 'idsr_diagnosis_id' => 34, 'icd_code' => 'A02.9', 'status' => 1],
                ['id' => 227, 'idsr_diagnosis_id' => 35, 'icd_code' => 'T63.0', 'status' => 1],
                ['id' => 228, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20', 'status' => 1],
                ['id' => 229, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.0', 'status' => 1],
                ['id' => 230, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.1', 'status' => 1],
                ['id' => 231, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.2', 'status' => 1],
                ['id' => 232, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.3', 'status' => 1],
                ['id' => 233, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.4', 'status' => 1],
                ['id' => 234, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.5', 'status' => 1],
                ['id' => 235, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.6', 'status' => 1],
                ['id' => 236, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.7', 'status' => 1],
                ['id' => 237, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.8', 'status' => 1],
                ['id' => 238, 'idsr_diagnosis_id' => 35, 'icd_code' => 'X20.9', 'status' => 1],
            ];

            DB::table('idsr_icd_mapping')->insert(array_map(
                fn ($row) => $row + ['created_at' => $now, 'updated_at' => $now],
                $mappings
            ));
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('idsr_icd_mapping');
        Schema::dropIfExists('idsr_diagnoses');
    }
};
