<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>DTC Monthly Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #2196f3;
        }
        .facility-info {
            margin-bottom: 20px;
            border-top: 2px solid #2196f3;
            border-bottom: 2px solid #2196f3;
            padding: 10px 0;
        }
        .facility-info p {
            margin: 5px 0;
        }
        .summary-section {
            margin: 20px 0;
        }
        .summary-section h2 {
            background-color: #f0f0f0;
            padding: 10px;
            margin: 0 0 10px 0;
            border-left: 4px solid #2196f3;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th {
            background-color: #2196f3;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>DTC (Diarrhea Treatment Center) Monthly Report</h1>
        <p>Diarrhea Cases and Patient Demographics</p>
    </div>

    <div class="facility-info">
        <p><strong>Facility:</strong> {{ $facility['name'] ?? 'N/A' }}</p>
        <p><strong>Region:</strong> {{ $facility['region'] ?? 'N/A' }}</p>
        <p><strong>District:</strong> {{ $facility['district'] ?? 'N/A' }}</p>
        <p><strong>Report Period:</strong> {{ $month_name }} {{ $year }}</p>
        <p><strong>Generated:</strong> {{ $generated_at->format('d M Y H:i') }}</p>
    </div>

    @if(isset($by_age_gender))
    <div class="summary-section">
        <h2>Diarrhea Cases by Age & Gender</h2>
        <table>
            <thead>
                <tr>
                    <th>Age Group</th>
                    <th class="text-center">Male</th>
                    <th class="text-center">Female</th>
                    <th class="text-center">Total</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($by_age_gender as $row)
                <tr>
                    <td>{{ $row['age_group'] }}</td>
                    <td>{{ $row['male'] ?? 0 }}</td>
                    <td>{{ $row['female'] ?? 0 }}</td>
                    <td><strong>{{ $row['total'] ?? 0 }}</strong></td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="text-center">No diarrhea cases reported</td>
                </tr>
                @endforelse
                @if(isset($totals))
                <tr style="background-color: #f0f0f0;">
                    <td><strong>Total</strong></td>
                    <td><strong>{{ $totals['male'] ?? 0 }}</strong></td>
                    <td><strong>{{ $totals['female'] ?? 0 }}</strong></td>
                    <td><strong>{{ $totals['total'] ?? 0 }}</strong></td>
                </tr>
                @endif
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This report was automatically generated by Practice 1.0 Health Information System</p>
        <p>For official use only. Confidential information.</p>
    </div>
</body>
</html>
