<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>IDSR Weekly Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #1f3a93;
        }
        .facility-info {
            margin-bottom: 20px;
            border-top: 2px solid #1f3a93;
            border-bottom: 2px solid #1f3a93;
            padding: 10px 0;
        }
        .facility-info p {
            margin: 5px 0;
        }
        .summary-section {
            margin: 20px 0;
        }
        .summary-section h2 {
            background-color: #f0f0f0;
            padding: 10px;
            margin: 0 0 10px 0;
            border-left: 4px solid #1f3a93;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th {
            background-color: #1f3a93;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>IDSR Weekly Report</h1>
        <p>Integrated Disease Surveillance and Response</p>
    </div>

    <div class="facility-info">
        <p><strong>Facility:</strong> {{ $facility['name'] ?? 'N/A' }}</p>
        <p><strong>Region:</strong> {{ $facility['region'] ?? 'N/A' }}</p>
        <p><strong>District:</strong> {{ $facility['district'] ?? 'N/A' }}</p>
        <p><strong>Report Period:</strong> Week {{ $week }} {{ $year }}</p>
        <p><strong>Generated:</strong> {{ $generated_at->format('d M Y H:i') }}</p>
    </div>

    @if(isset($diseases) && count($diseases) > 0)
        @forelse ($diseases as $disease_name => $disease_data)
        <div class="summary-section">
            <h2>{{ $disease_name }}</h2>
            <p><strong>Total Cases:</strong> {{ $disease_data['total_cases'] ?? 0 }}</p>
            <table>
                <thead>
                    <tr>
                        <th>Age Group</th>
                        <th class="text-center">Male</th>
                        <th class="text-center">Female</th>
                        <th class="text-center">Total</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($disease_data['by_age_gender'] ?? [] as $case)
                    <tr>
                        <td>{{ $case['age_group'] }}</td>
                        <td>{{ $case['male'] ?? 0 }}</td>
                        <td>{{ $case['female'] ?? 0 }}</td>
                        <td>{{ $case['total'] ?? 0 }}</td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" class="text-center">No cases reported</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        @empty
        <div class="summary-section">
            <p>No disease cases reported this week</p>
        </div>
        @endforelse
    @endif

    <div class="footer">
        <p>This report was automatically generated by Practice 1.0 Health Information System</p>
        <p>For official use only. Confidential information.</p>
    </div>
</body>
</html>
