<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Serology Lab Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #1f3a93;
        }
        .facility-info {
            margin-bottom: 20px;
            border-top: 2px solid #1f3a93;
            border-bottom: 2px solid #1f3a93;
            padding: 10px 0;
        }
        .facility-info p {
            margin: 5px 0;
        }
        .summary-section {
            margin: 20px 0;
        }
        .summary-section h2 {
            background-color: #f0f0f0;
            padding: 10px;
            margin: 0 0 10px 0;
            border-left: 4px solid #1f3a93;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th {
            background-color: #1f3a93;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Serology Laboratory Report</h1>
        <p>Monthly Test Results and Statistics</p>
    </div>

    <div class="facility-info">
        <p><strong>Facility:</strong> {{ $facility['name'] ?? 'N/A' }}</p>
        <p><strong>Region:</strong> {{ $facility['region'] ?? 'N/A' }}</p>
        <p><strong>District:</strong> {{ $facility['district'] ?? 'N/A' }}</p>
        <p><strong>Report Period:</strong> {{ $month_name }} {{ $year }}</p>
        <p><strong>Generated:</strong> {{ $generated_at->format('d M Y H:i') }}</p>
    </div>

    <div class="summary-section">
        <h2>Summary Statistics</h2>
        <table>
            <tr>
                <td><strong>Total Tests:</strong></td>
                <td>{{ $total_tests }}</td>
                <td><strong>Completed:</strong></td>
                <td>{{ $completed_tests }}</td>
            </tr>
            <tr>
                <td><strong>Pending:</strong></td>
                <td>{{ $pending_tests }}</td>
                <td><strong>Completion Rate:</strong></td>
                <td>{{ $completion_rate }}%</td>
            </tr>
        </table>
    </div>

    @if (count($investigations) > 0)
    <div class="summary-section">
        <h2>Detailed Test Results</h2>
        <table>
            <thead>
                <tr>
                    <th>Test Name</th>
                    <th>Patient ID</th>
                    <th>Visit Date</th>
                    <th>Status</th>
                    <th>Result Value</th>
                    <th>Unit</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($investigations as $inv)
                <tr>
                    <td>{{ $inv['test_name'] }}</td>
                    <td>{{ $inv['patient_id'] }}</td>
                    <td>{{ $inv['visit_date'] }}</td>
                    <td>{{ $inv['status'] ?? 'Pending' }}</td>
                    <td>{{ $inv['result_value'] ?? '-' }}</td>
                    <td>{{ $inv['result_unit'] ?? '-' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This report was automatically generated by Practice 1.0 Health Information System</p>
        <p>For official use only. Confidential information.</p>
    </div>
</body>
</html>
