<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Low Stock Medicines Alert Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #c0392b;
        }
        .facility-info {
            margin-bottom: 20px;
            border-top: 2px solid #c0392b;
            border-bottom: 2px solid #c0392b;
            padding: 10px 0;
        }
        .facility-info p {
            margin: 5px 0;
        }
        .summary-section {
            margin: 20px 0;
        }
        .summary-section h2 {
            background-color: #f0f0f0;
            padding: 10px;
            margin: 0 0 10px 0;
            border-left: 4px solid #c0392b;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th {
            background-color: #c0392b;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-out-of-stock {
            background-color: #ffcccc;
            color: #c0392b;
            font-weight: bold;
        }
        .status-low-stock {
            background-color: #ffffcc;
            color: #d68910;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Low Stock Medicines Alert Report</h1>
        <p>Inventory Stock Status and Action Required</p>
    </div>

    <div class="facility-info">
        <p><strong>Facility:</strong> {{ $facility['name'] ?? 'N/A' }}</p>
        <p><strong>Region:</strong> {{ $facility['region'] ?? 'N/A' }}</p>
        <p><strong>District:</strong> {{ $facility['district'] ?? 'N/A' }}</p>
        <p><strong>Report Generated:</strong> {{ now()->format('d M Y H:i') }}</p>
    </div>

    @if(isset($out_of_stock) && count($out_of_stock) > 0)
    <div class="summary-section">
        <h2>Out of Stock Items</h2>
        <table>
            <thead>
                <tr>
                    <th>Medication Name</th>
                    <th class="text-center">Current Stock</th>
                    <th class="text-center">Reorder Level</th>
                    <th class="text-center">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($out_of_stock as $med)
                <tr>
                    <td>{{ $med['name'] ?? 'Unknown' }}</td>
                    <td>{{ $med['stock_quantity'] ?? 0 }}</td>
                    <td>{{ $med['reorder_level'] ?? 0 }}</td>
                    <td class="status-out-of-stock">OUT OF STOCK</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    @if(isset($low_stock) && count($low_stock) > 0)
    <div class="summary-section">
        <h2>Low Stock Items</h2>
        <table>
            <thead>
                <tr>
                    <th>Medication Name</th>
                    <th class="text-center">Current Stock</th>
                    <th class="text-center">Reorder Level</th>
                    <th class="text-center">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($low_stock as $med)
                <tr>
                    <td>{{ $med['name'] ?? 'Unknown' }}</td>
                    <td>{{ $med['stock_quantity'] ?? 0 }}</td>
                    <td>{{ $med['reorder_level'] ?? 0 }}</td>
                    <td class="status-low-stock">LOW STOCK</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This report was automatically generated by Practice 1.0 Health Information System</p>
        <p>For official use only. Confidential information.</p>
    </div>
</body>
</html>
