<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Medicines Monthly Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #27ae60;
        }
        .facility-info {
            margin-bottom: 20px;
            border-top: 2px solid #27ae60;
            border-bottom: 2px solid #27ae60;
            padding: 10px 0;
        }
        .facility-info p {
            margin: 5px 0;
        }
        .summary-section {
            margin: 20px 0;
        }
        .summary-section h2 {
            background-color: #f0f0f0;
            padding: 10px;
            margin: 0 0 10px 0;
            border-left: 4px solid #27ae60;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th {
            background-color: #27ae60;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Medicines Monthly Report</h1>
        <p>Medication Consumption and Dispensing Summary</p>
    </div>

    <div class="facility-info">
        <p><strong>Facility:</strong> {{ $facility['name'] ?? 'N/A' }}</p>
        <p><strong>Region:</strong> {{ $facility['region'] ?? 'N/A' }}</p>
        <p><strong>District:</strong> {{ $facility['district'] ?? 'N/A' }}</p>
        <p><strong>Report Period:</strong> {{ $month_name }} {{ $year }}</p>
        <p><strong>Generated:</strong> {{ $generated_at->format('d M Y H:i') }}</p>
    </div>

    @if(isset($by_category))
    <div class="summary-section">
        <h2>Medications by Category</h2>
        <table>
            <thead>
                <tr>
                    <th>Category</th>
                    <th class="text-center">Total Prescribed</th>
                    <th class="text-center">Total Dispensed</th>
                    <th class="text-center">Quantity Dispensed</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($by_category as $cat)
                <tr>
                    <td>{{ $cat['category'] }}</td>
                    <td>{{ $cat['total_prescribed'] ?? 0 }}</td>
                    <td>{{ $cat['total_dispensed'] ?? 0 }}</td>
                    <td>{{ $cat['total_quantity'] ?? 0 }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="text-center">No medication data</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    @endif

    @if(isset($top_medicines))
    <div class="summary-section">
        <h2>Top Medications Dispensed</h2>
        <table>
            <thead>
                <tr>
                    <th>Medication Name</th>
                    <th class="text-center">Times Dispensed</th>
                    <th class="text-center">Total Quantity</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($top_medicines as $med)
                <tr>
                    <td>{{ $med['medication_name'] }}</td>
                    <td>{{ $med['times_dispensed'] ?? 0 }}</td>
                    <td>{{ $med['total_quantity'] ?? 0 }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="3" class="text-center">No medication data</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This report was automatically generated by Practice 1.0 Health Information System</p>
        <p>For official use only. Confidential information.</p>
    </div>
</body>
</html>
